server:
  port: 8083
  servlet:
    context-path: /client2
security:
  oauth2:
    client:
      client-id: corner2
      client-secret: aaa2
      user-authorization-uri: http://localhost:8081/server/oauth/authorize
      access-token-uri: http://localhost:8081/server/oauth/token
    resource:
      jwt:
        key-uri:  http://localhost:8081/server/oauth/token_key
